let title="student detail";
let name="abi";
let age=20;
let bloodgroup="O-ve";
let collegename="PSN college of engineering and technology";
let city="tirunelveli";
let dept="ECE";
let year="third year";
let sem="5th";
let phoneno=8667002205;
console.log("title:",title);
console.log("name:",name);
console.log("age:",age);
console.log("bloodgroup:",bloodgroup);
console.log("collegename:",collegename);
console.log("city:",city);
console.log("dept:",dept);
console.log("year:",year);
console.log("sem:",sem);
console.log("phoneno:",phoneno);
